name: Generar gráfico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
        ports:
          - 9200:9200
        options: >-
          --env discovery.type=single-node
          --env xpack.security.enabled=false

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib elasticsearch

      - name: Ejecutar script
        run: python ElasticSearch.py

      - name: Commit y push de gráficos
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/grafico.png
          git commit -m "Actualizar gráfico" || echo "No hay cambios para commitear"
          git push
