name: Generate Visualizations and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar semanalmente
  workflow_dispatch:       # Permitir ejecución manual

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install elasticsearch pandas matplotlib seaborn numpy
        
    - name: Run ElasticSearch script
      env:
        ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
        ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
        ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
      run: |
        python ElasticSearch.py
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs