name: Generar gráfico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib elasticsearch numpy

    - name: Crear carpeta docs (por si acaso)
      run: mkdir -p docs

    - name: Ejecutar script
      run: python ElasticSearch.py

    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit y push de gráficos
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/BrianPech99/Portafolio.git
        if [ -f docs/grafico.png ]; then
          git add docs/grafico.png
          git commit -m "Actualizar gráfico" || echo "No hay cambios para commitear"
          git push origin main
        else
          echo "docs/grafico.png no existe — no se realiza commit/push"
        fi