name: Generar gráfico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib elasticsearch

    - name: Ejecutar script
      run: python ElasticSearch.py

    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit y push de gráficos
      run: |
        git add docs/grafico.png
        git commit -m "Actualizar gráfico" || echo "No hay cambios para commitear"
        git push
